# Generated by Django 5.0.9 on 2025-11-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='extracted_text',
            new_name='elements',
        ),
    ]
