# Generated by Django 5.0.9 on 2025-11-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0003_rename_extracted_text_document_elements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='layout_json',
            new_name='layout',
        ),
        migrations.RemoveField(
            model_name='document',
            name='elements',
        ),
    ]
